apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nameCluster
  region: ap-southeast-1
  version: "1.21"

vpc:
  id: "vpc-id"
  subnets:
    private:
      ap-southeast-1a: { id: subnet-id }
      ap-southeast-1b: { id: subnet-id }
      ap-southeast-1c: { id: subnet-id }

nodeGroups:
  - name: nodeGroup
    instanceType: t4g.small
    minSize: 3
    maxSize: 5
    desiredCapacity: 3
    volumeSize: 30
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: key
    iam:
      withAddonPolicies:
        ebs: true
        certManager: true
        autoScaler: true
        efs: true
        elb: true