apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  use-forwarded-headers: "true"
  enable-real-ip: "true"
  hide-headers: X-Powered-By
  proxy_pass_request_headers: "on"
  enable-underscores-in-headers: "true"